# Generated by Django 2.2 on 2021-06-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210608_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tenant_node',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tenant_uuid',
        ),
        migrations.AlterField(
            model_name='client',
            name='domain_url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
